version: 2
 
sources:
  - name: source_raw
    database: dbt_project_casestudy  
    schema: source_raw
    tables:
      - name: prod_mstr_pna1
      - name: cust_mstr_kna1
      - name: cust_mstr_tkna1
      - name: prod_mstr_tpna1
      - name: invoice_raw